language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5-dev"
  - "nightly"
  - "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install coveralls
#  - pip install coverage
script:
  - python setup.py test # coverage run
after_success:
  - coveralls
