language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
  - "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install coveralls
  - pip install coverage
script:
  - coverage run setup.py test
after_success:
  - coveralls
